# Generated by Django 4.0.4 on 2022-06-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_address_order'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipment_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart_status_field',
            field=models.CharField(choices=[('Not purchased', 'Not purchased'), ('purchased', 'purchased'), ('in progress', 'in progress')], default='Not purchased', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='address_set', to='accounts.address'),
        ),
        migrations.AddField(
            model_name='payment',
            name='shipment_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('pishtaz', 'Pishtaz'), ('tipax', 'Tipax')], default='regular', max_length=100),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
