# Generated by Django 4.0.4 on 2022-05-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='order_set', to='orders.order'),
        ),
        migrations.AddField(
            model_name='address',
            name='supplier_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier'),
        ),
    ]
