version: "3.7"

services:
  ecommerce-lakers:
    build: .
    command: >
      bash -c "python manage.py migrate && gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/app/static
      - media:/app/media
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
#    depends_on:
#      - postgres_db

#  postgres_db:
#    image: postgres:latest
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=arian
#      - POSTGRES_PASSWORD=arian
#      - POSTGRES_DB=shop

  nginx:
    build: .
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - 8082:80
    depends_on:
      - ecommerce-lakers

  redis:
    image: redis:latest

  celery:
    restart: always
    build:
      context: .
    command: >
      bash -c "touch celery.log && touch celery_beat.log && celery -A ecommerce worker -l info &> celery.log"
    volumes:
      - .:/app
    depends_on:
      - ecommerce-lakers
      - redis
volumes:
  static:
  media: